// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vukzizuukbpwzzfuzini.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1a3ppenV1a2Jwd3p6ZnV6aW5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMzQyNTAsImV4cCI6MjA2MjcxMDI1MH0.tAVsJuukWPkNqWDyJO5un8K6D_-w3ZJIEsCC7weAdpQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);